module.exports = {
  userExists: { message: 'Usuário já existe' },
  userNotExists: { message: 'Usuário não existe' },
  invalidDisplayName: { message: '"displayName" length must be at least 8 characters long' },
  invalidEmail: { message: '"email" must be a valid email' },
  missingEmail: { message: '"email" is required' },
  emptyEmail: { message: '"email" is not allowed to be empty' },
  invalidPassword: { message: '"password" length must be 6 characters long' },
  missingPassword: { message: '"password" is required' },
  emptyPassword: { message: '"password" is not allowed to be empty' },
  invalidFields: { message: 'Campos inválidos' },
  missingToken: { message: 'Token não encontrado' },
  invalidToken: { message: 'Token expirado ou inválido' },
  missingTitle: { message: '"title" is required' },
  missingContent: { message: '"content" is required' },
  missingPost: { message: 'Post não existe' },
};
